============================= test session starts ==============================
platform darwin -- Python 3.6.5, pytest-3.10.0, py-1.7.0, pluggy-0.8.0
rootdir: /Users/alberta/Developer/git/codesignals/python/challenges/robotVacuum, inifile:
plugins: timeout-1.3.2
collected 6 items

test/test_algo.py .....FE                                                [100%]

==================================== ERRORS ====================================
_______________ ERROR at teardown of TestAglo.test_robotVacuum_5 _______________

self = <contextlib._GeneratorContextManager object at 0x107c8a438>, type = None
value = None, traceback = None

    def __exit__(self, type, value, traceback):
        if type is None:
            try:
>               next(self.gen)
E               OSError: [Errno 22] Invalid argument

/Users/alberta/.pyenv/versions/3.6.5/lib/python3.6/contextlib.py:88: OSError
=================================== FAILURES ===================================
_________________________ TestAglo.test_robotVacuum_5 __________________________

self = <contextlib._GeneratorContextManager object at 0x108b68b70>, type = None
value = None, traceback = None

    def __exit__(self, type, value, traceback):
        if type is None:
            try:
>               next(self.gen)
E               OSError: [Errno 22] Invalid argument

/Users/alberta/.pyenv/versions/3.6.5/lib/python3.6/contextlib.py:88: OSError
================ 1 failed, 5 passed, 1 error in 182.39 seconds =================
